variable "region" {}
variable "environment" {}
variable "aws_prefix" {}
variable "lambda_function_handler_name" {}
variable "smtpInfo_Host" {}
variable "smtpInfo_Port" {}
variable "smtpInfo_DisplayName" {}
variable "smtpInfo_Username" {}
variable "smtpInfo_Password" {}
variable "smtpInfo_UseSSL" {}
variable "profile_Name" {}
variable "profile_Email" {}
variable "profile_Contact" {}
variable "profile_LinkedIn" {}
variable "profile_GitHub" {}
variable "profile_Address" {}
variable "profile_Website" {}
variable "cors_Origins" {}
variable "tags_deployment_source" {}
variable "dotnet_runtime" {}
